# Generated by Django 5.2.1 on 2025-05-12 20:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MobileAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("bkash", "bKash"), ("nagad", "Nagad")], max_length=10
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("account_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                (
                    "account_type",
                    models.CharField(
                        choices=[("personal", "Personal"), ("agent", "Agent")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdraw", "Withdraw")],
                        max_length=10,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("card", "Card"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "flat_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
            ],
            options={
                "unique_together": {("method_type", "payment_type")},
            },
        ),
    ]
