# Generated by Django 5.2.1 on 2025-05-12 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mobile_bankings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_type",
                    models.CharField(
                        choices=[("wallet", "Wallet"), ("card", "Card")], max_length=10
                    ),
                ),
                ("from_id", models.IntegerField()),
                (
                    "to_type",
                    models.CharField(
                        choices=[("wallet", "Wallet"), ("mobile", "Mobile")],
                        max_length=10,
                    ),
                ),
                ("to_id", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdraw", "Withdraw")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fee_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "fee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile_bankings.fee",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
